theme: jekyll-theme-minimal
title: Auto-Generate Map of BLE Beacons for Indoor Positioning Using a Phone’s Motion Sensors
description: by Max Gong

Table of Contents
<a href="https://maxgong21.github.io/ecem202a-project/#abstract">Abstract</a>


